version: "3.8"

networks:
  mynetwork:
    driver: bridge

services:
  db:
    image: postgres:17
    container_name: url_shortener
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
